# Generated by Django 4.0.4 on 2022-04-26 05:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(max_length=256)),
                ('docurl', models.CharField(max_length=256)),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='InProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('cost', models.BigIntegerField()),
                ('count', models.BigIntegerField()),
                ('document', models.CharField(max_length=256)),
                ('date', models.DateField(default=datetime.date.today)),
                ('picture', models.CharField(max_length=256)),
                ('receiverperson', models.CharField(max_length=128)),
                ('transmitterperson', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='OutProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('getproductperson', models.CharField(max_length=256)),
                ('whoperson', models.CharField(max_length=256)),
                ('cost', models.BigIntegerField()),
                ('count', models.BigIntegerField()),
                ('document', models.CharField(max_length=256)),
                ('date', models.DateField(default=datetime.date.today)),
                ('picture', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itm.departments')),
            ],
        ),
    ]
