# Generated by Django 4.0.4 on 2022-04-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inproductlist',
            name='unit',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
