# Generated by Django 4.0.4 on 2022-04-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itm', '0003_outproductlist_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
